---
title: "Two Parameter Logistic Model"
author: "Erick A. Chacon-Montalvan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Two Parameter Logistic Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
knitr::opts_chunk$set(fig.width = 6, fig.height = 4)
# knitr::opts_chunk$set(fig.width = 6, fig.height = 4)
knitr::opts_chunk$set(comment = "#>")
options(width = 100)
```


In this vignette, we show how to use the package to fit a 2 parameter model.

## Required packages

```{r}
rm(list = ls())
library(spmirt)
library(datasim)
library(coda)
library(tidyverse)
```

# Example 1

## Simulation of the data

```{r}
q <- q1 <- q2 <- 10
n <- 300
difficulty <- matrix((1:q - 5)/10 * 2, nrow = 1)
discrimination1 <- matrix(seq(0.4, 1.5, length.out = q), nrow = 1)
discrimination2 <- matrix(runif(q, 0, 1.5), nrow = 1)

f <- list(
  prob ~ mfa(ones, beta = get("difficulty")) +
    re(id, sigma = 1, q = get("q1")):mfa(ones, beta = get("discrimination1")) +
    re(id, sigma = 1, q = get("q2")):mfa(ones, beta = get("discrimination2")),
  size ~ I(1)
  )

data_long <- sim_model(formula = f,
                        link_inv = list(pnorm, identity),
                        generator = rbinom,
                        responses = q,
                        n = n)
# ,
#                         seed = 1)

data_long <- dplyr::rename(data_long, subject = id, ability1 = re.id.prob,
                           ability2 = re.id.prob.1,
                           item = response_label, y = response)
```

```{r, echo = FALSE, results = 'asis'}
knitr::kable(head(data_long, 20))
```

```{r}
explor <- data_long %>%
  group_by(subject) %>%
  summarize(endorse = mean(y), ability1 = unique(ability1), ability2 = unique(ability2))
ggplot(explor, aes(ability1, endorse)) + geom_point()
ggplot(explor, aes(ability2, endorse)) + geom_point()
```


## Fitting the model

```{r}
iter <- 10
system.time(samples <- ifa_gibbs(data_long$y, n, q, iter, 2))
purrr::map(samples, dim)
```

```{r}
plot(samples$theta[, 1 + c(1, 301)])
points(0, 0, pch = 19, col = 2)
points(samples$theta[, 2 + c(1, 301)], col = 3)
points(samples$theta[, 3 + c(1, 301)], col = 4)
points(samples$theta[, 4 + c(1, 301)], col = 5)
points(samples$theta[, 5 + c(1, 301)], col = 6)
points(samples$theta[, 6 + c(1, 301)], col = 7)

# plot(samples$theta[, 17 + c(1, 301)], type = "b", col = rgb(0, 0, 0, 0.2))
plot(samples$theta[, 6 + c(1, 301)], type = "b", col = rgb(0, 0, 0, 0.2))
points(0, 0, pch = 19, col = 2)

plot(samples$a[, 0 + c(1, 11)], type = "b", col = rgb(0, 0, 0, 0.1))
points(0, 0, pch = 19, col = 2)


plot(samples$a[, 1 + c(1, 11)], type = "b", col = rgb(0, 0, 0, 0.1))
points(0, 0, pch = 19, col = 2)

plot(samples$a[, 2 + c(1, 11)], type = "b", col = rgb(0, 0, 0, 0.1))
points(0, 0, pch = 19, col = 2)

plot(samples$a[, 3 + c(1, 11)], type = "b", col = rgb(0, 0, 0, 0.1))
points(0, 0, pch = 19, col = 2)

plot(samples$a[, 4 + c(1, 11)], type = "b", col = rgb(0, 0, 0, 0.1))
points(0, 0, pch = 19, col = 2)

plot(samples$a[, 5 + c(1, 11)], type = "b", col = rgb(0, 0, 0, 0.1))
points(0, 0, pch = 19, col = 2)

plot(samples$a[, 6 + c(1, 11)], type = "b", col = rgb(0, 0, 0, 0.1))
points(0, 0, pch = 19, col = 2)

k <- 1
image(MASS::kde2d(samples$a[, k], samples$a[, k + 10], n = 100))

k <- 2
image(MASS::kde2d(samples$a[, k], samples$a[, k + 10], n = 100))

k <- 4
image(MASS::kde2d(samples$a[, k], samples$a[, k + 10], n = 100))

k <- 5
image(MASS::kde2d(samples$a[, k], samples$a[, k + 10], n = 100))

k <- 6
image(MASS::kde2d(samples$a[, k], samples$a[, k + 10], n = 100))

k <- 7
image(MASS::kde2d(samples$a[, k], samples$a[, k + 10], n = 100))

k <- 8
image(MASS::kde2d(samples$a[, k], samples$a[, k + 10], n = 100))

k <- 9
image(MASS::kde2d(samples$a[, k], samples$a[, k + 10], n = 100))
```

## Evaluate the results

```{r}

# Organize and summarise output
samples_after_burin <- samples %>% purrr::map(~ .[(0.6 * iter):iter, ])
samples_params <- samples_after_burin[1:3]
samples_params_summary <- samples_params %>%
  map(~ apply(., 2, function (x) quantile(x, c(0.025, 0.5, 0.975)))) %>%
  map(~ as_tibble(t(.))) %>%
  map(~ setNames(., make.names(names(.))))

# Visualize convergence
opar <- par(mfrow = c(2, 2), mar = c(2, 1.9, 2, 0.6))
map(samples_after_burin, ~ plot(mcmc(.[, 1:5]), auto.layout = FALSE))
par(opar)

# Matching parameters
samples_params_summary$theta <- samples_params_summary$theta %>%
  mutate(
    param1 = c(unique(data_long$ability1), unique(data_long$ability2)),
    param2 = c(unique(data_long$ability1), - unique(data_long$ability2)),
    param3 = c(- unique(data_long$ability1), unique(data_long$ability2)),
    param4 = - c(unique(data_long$ability1), unique(data_long$ability2)),
    param5 = c(unique(data_long$ability2), unique(data_long$ability1)),
    param6 = c(unique(data_long$ability2), - unique(data_long$ability1)),
    param7 = c(- unique(data_long$ability2), unique(data_long$ability1)),
    param8 = - c(unique(data_long$ability2), unique(data_long$ability1)),
         )
samples_params_summary$a <- samples_params_summary$a %>%
  mutate(
    param1 = c(discrimination1, discrimination2),
    param2 = c(discrimination1, - discrimination2),
    param3 = c(- discrimination1, discrimination2),
    param4 = - c(discrimination1, discrimination2),
    param5 = c(discrimination2, discrimination1),
    param6 = c(discrimination2, - discrimination1),
    param7 = c(- discrimination2, discrimination1),
    param8 = - c(discrimination2, discrimination1),
         )
samples_params_summary$c$param <- c(difficulty)

# Visualize results
samples_params_summary$theta %>% gather(key, param, param1:param4) %>%
  ggplot(., aes(X50., param)) +
    geom_errorbar(aes(ymin = X2.5., ymax = X97.5.)) +
    geom_point(col = 2) +
    facet_wrap(~ key)
samples_params_summary$theta %>% gather(key, param, param5:param8) %>%
  ggplot(., aes(X50., param)) +
    geom_errorbar(aes(ymin = X2.5., ymax = X97.5.)) +
    geom_point(col = 2) +
    facet_wrap(~ key)

samples_params_summary$a %>% gather(key, param, param1:param4) %>%
  ggplot(., aes(X50., param)) +
    geom_errorbar(aes(ymin = X2.5., ymax = X97.5.)) +
    geom_point(col = 2) +
    facet_wrap(~ key)
samples_params_summary$a %>% gather(key, param, param5:param8) %>%
  ggplot(., aes(X50., param)) +
    geom_errorbar(aes(ymin = X2.5., ymax = X97.5.)) +
    geom_point(col = 2) +
    facet_wrap(~ key)


samples_params_summary$c %>%
  ggplot(., aes(X50., param)) +
    geom_errorbar(aes(ymin = X2.5., ymax = X97.5.)) +
    geom_point(col = 2)


```

Correlation

```{r}
ability_real <- matrix(unique(c(data_long$ability1, data_long$ability2)), ncol = 2)
ability_estimate <- matrix(samples_params_summary$theta$X50., ncol = 2)
cor(ability_real)
cor(ability_estimate)
cov(ability_real)
cov(ability_estimate)

A <- cbind(c(discrimination1), c(discrimination2))
solve(crossprod(A) + diag(1, 2))

tcrossprod(A)

A_est <- matrix(samples_params_summary$a$X50., ncol = 2)

plot(tcrossprod(A), tcrossprod(A_est))
abline(0, 1)


```
