// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// vec2mat
arma::mat vec2mat(arma::vec x, int nrow, int ncol);
RcppExport SEXP _spmirt_vec2mat(SEXP xSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(vec2mat(x, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// vec2matt
arma::mat vec2matt(arma::vec x, int nrow, int ncol);
RcppExport SEXP _spmirt_vec2matt(SEXP xSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(vec2matt(x, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// vecsub
arma::vec vecsub(arma::vec x, int first_index, int n_length);
RcppExport SEXP _spmirt_vecsub(SEXP xSEXP, SEXP first_indexSEXP, SEXP n_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type first_index(first_indexSEXP);
    Rcpp::traits::input_parameter< int >::type n_length(n_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(vecsub(x, first_index, n_length));
    return rcpp_result_gen;
END_RCPP
}
// vecsub1
double vecsub1(arma::vec x, int index);
RcppExport SEXP _spmirt_vecsub1(SEXP xSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(vecsub1(x, index));
    return rcpp_result_gen;
END_RCPP
}
// matsub1
double matsub1(arma::mat x, int index_row, int index_col);
RcppExport SEXP _spmirt_matsub1(SEXP xSEXP, SEXP index_rowSEXP, SEXP index_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type index_row(index_rowSEXP);
    Rcpp::traits::input_parameter< int >::type index_col(index_colSEXP);
    rcpp_result_gen = Rcpp::wrap(matsub1(x, index_row, index_col));
    return rcpp_result_gen;
END_RCPP
}
// subset_cpp
Rcpp::List subset_cpp(arma::mat X, arma::vec y);
RcppExport SEXP _spmirt_subset_cpp(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(subset_cpp(X, y));
    return rcpp_result_gen;
END_RCPP
}
// vec2trimatl
arma::mat vec2trimatl(arma::vec x, int K, bool diag);
RcppExport SEXP _spmirt_vec2trimatl(SEXP xSEXP, SEXP KSEXP, SEXP diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type diag(diagSEXP);
    rcpp_result_gen = Rcpp::wrap(vec2trimatl(x, K, diag));
    return rcpp_result_gen;
END_RCPP
}
// trimatl2vec
arma::vec trimatl2vec(arma::mat L, bool diag);
RcppExport SEXP _spmirt_trimatl2vec(SEXP LSEXP, SEXP diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< bool >::type diag(diagSEXP);
    rcpp_result_gen = Rcpp::wrap(trimatl2vec(L, diag));
    return rcpp_result_gen;
END_RCPP
}
// vec2chol_corr
arma::mat vec2chol_corr(arma::vec x, int K);
RcppExport SEXP _spmirt_vec2chol_corr(SEXP xSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(vec2chol_corr(x, K));
    return rcpp_result_gen;
END_RCPP
}
// chol_corr2vec
arma::vec chol_corr2vec(arma::mat L_chol);
RcppExport SEXP _spmirt_chol_corr2vec(SEXP L_cholSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L_chol(L_cholSEXP);
    rcpp_result_gen = Rcpp::wrap(chol_corr2vec(L_chol));
    return rcpp_result_gen;
END_RCPP
}
// probit_gp_adap
Rcpp::List probit_gp_adap(Rcpp::NumericVector y, arma::mat dist, arma::vec params, int iter, arma::mat Sigma_proposal);
RcppExport SEXP _spmirt_probit_gp_adap(SEXP ySEXP, SEXP distSEXP, SEXP paramsSEXP, SEXP iterSEXP, SEXP Sigma_proposalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist(distSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_proposal(Sigma_proposalSEXP);
    rcpp_result_gen = Rcpp::wrap(probit_gp_adap(y, dist, params, iter, Sigma_proposal));
    return rcpp_result_gen;
END_RCPP
}
// probit_gp
Rcpp::List probit_gp(Rcpp::NumericVector y, arma::mat dist, arma::vec params, int iter, arma::mat Sigma_proposal);
RcppExport SEXP _spmirt_probit_gp(SEXP ySEXP, SEXP distSEXP, SEXP paramsSEXP, SEXP iterSEXP, SEXP Sigma_proposalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist(distSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_proposal(Sigma_proposalSEXP);
    rcpp_result_gen = Rcpp::wrap(probit_gp(y, dist, params, iter, Sigma_proposal));
    return rcpp_result_gen;
END_RCPP
}
// probit_gp_chol2
Rcpp::List probit_gp_chol2(Rcpp::NumericVector y, arma::mat dist, arma::vec params, int iter, arma::mat Sigma_proposal);
RcppExport SEXP _spmirt_probit_gp_chol2(SEXP ySEXP, SEXP distSEXP, SEXP paramsSEXP, SEXP iterSEXP, SEXP Sigma_proposalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist(distSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_proposal(Sigma_proposalSEXP);
    rcpp_result_gen = Rcpp::wrap(probit_gp_chol2(y, dist, params, iter, Sigma_proposal));
    return rcpp_result_gen;
END_RCPP
}
// probit_gp_chol
Rcpp::List probit_gp_chol(Rcpp::NumericVector y, arma::mat dist, arma::vec params, int iter, arma::mat Sigma_proposal);
RcppExport SEXP _spmirt_probit_gp_chol(SEXP ySEXP, SEXP distSEXP, SEXP paramsSEXP, SEXP iterSEXP, SEXP Sigma_proposalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist(distSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_proposal(Sigma_proposalSEXP);
    rcpp_result_gen = Rcpp::wrap(probit_gp_chol(y, dist, params, iter, Sigma_proposal));
    return rcpp_result_gen;
END_RCPP
}
// logit
double logit(double p);
RcppExport SEXP _spmirt_logit(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(logit(p));
    return rcpp_result_gen;
END_RCPP
}
// logistic
double logistic(double x);
RcppExport SEXP _spmirt_logistic(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic(x));
    return rcpp_result_gen;
END_RCPP
}
// ifa_gibbs
Rcpp::List ifa_gibbs(Rcpp::NumericVector y, int n, int q, int N, int m);
RcppExport SEXP _spmirt_ifa_gibbs(SEXP ySEXP, SEXP nSEXP, SEXP qSEXP, SEXP NSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(ifa_gibbs(y, n, q, N, m));
    return rcpp_result_gen;
END_RCPP
}
// ifa_gibbs_nonide
Rcpp::List ifa_gibbs_nonide(Rcpp::NumericVector y, int n, int q, int N, int m);
RcppExport SEXP _spmirt_ifa_gibbs_nonide(SEXP ySEXP, SEXP nSEXP, SEXP qSEXP, SEXP NSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(ifa_gibbs_nonide(y, n, q, N, m));
    return rcpp_result_gen;
END_RCPP
}
// spifa_gibbs
Rcpp::List spifa_gibbs(Rcpp::NumericVector y, int n, int q, int N, int m);
RcppExport SEXP _spmirt_spifa_gibbs(SEXP ySEXP, SEXP nSEXP, SEXP qSEXP, SEXP NSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(spifa_gibbs(y, n, q, N, m));
    return rcpp_result_gen;
END_RCPP
}
// multi_lm
Rcpp::List multi_lm(Rcpp::NumericVector y, arma::mat dist, arma::vec params, int iter, arma::mat Sigma_proposal);
RcppExport SEXP _spmirt_multi_lm(SEXP ySEXP, SEXP distSEXP, SEXP paramsSEXP, SEXP iterSEXP, SEXP Sigma_proposalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dist(distSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_proposal(Sigma_proposalSEXP);
    rcpp_result_gen = Rcpp::wrap(multi_lm(y, dist, params, iter, Sigma_proposal));
    return rcpp_result_gen;
END_RCPP
}
// dmvnorm
double dmvnorm(arma::vec x, arma::vec mean, arma::mat sigma);
RcppExport SEXP _spmirt_dmvnorm(SEXP xSEXP, SEXP meanSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnorm(x, mean, sigma));
    return rcpp_result_gen;
END_RCPP
}
// dmvnorm_chol
double dmvnorm_chol(arma::vec x, arma::vec mean, arma::mat L);
RcppExport SEXP _spmirt_dmvnorm_chol(SEXP xSEXP, SEXP meanSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnorm_chol(x, mean, L));
    return rcpp_result_gen;
END_RCPP
}
// dmvnorm_cholinv
double dmvnorm_cholinv(arma::vec x, arma::vec mean, arma::mat L_inv);
RcppExport SEXP _spmirt_dmvnorm_cholinv(SEXP xSEXP, SEXP meanSEXP, SEXP L_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type L_inv(L_invSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnorm_cholinv(x, mean, L_inv));
    return rcpp_result_gen;
END_RCPP
}
// dmvnorm_prec
double dmvnorm_prec(arma::vec x, arma::vec mean, arma::mat sigma_inv);
RcppExport SEXP _spmirt_dmvnorm_prec(SEXP xSEXP, SEXP meanSEXP, SEXP sigma_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_inv(sigma_invSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnorm_prec(x, mean, sigma_inv));
    return rcpp_result_gen;
END_RCPP
}
// dinvwish
double dinvwish(double v, arma::mat X, arma::mat S);
RcppExport SEXP _spmirt_dinvwish(SEXP vSEXP, SEXP XSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(dinvwish(v, X, S));
    return rcpp_result_gen;
END_RCPP
}
// dlkj_corr
double dlkj_corr(arma::mat R, double eta, bool loglik);
RcppExport SEXP _spmirt_dlkj_corr(SEXP RSEXP, SEXP etaSEXP, SEXP loglikSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< bool >::type loglik(loglikSEXP);
    rcpp_result_gen = Rcpp::wrap(dlkj_corr(R, eta, loglik));
    return rcpp_result_gen;
END_RCPP
}
// dlkj_corr_chol
double dlkj_corr_chol(arma::mat L, double eta, bool loglik);
RcppExport SEXP _spmirt_dlkj_corr_chol(SEXP LSEXP, SEXP etaSEXP, SEXP loglikSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< bool >::type loglik(loglikSEXP);
    rcpp_result_gen = Rcpp::wrap(dlkj_corr_chol(L, eta, loglik));
    return rcpp_result_gen;
END_RCPP
}
// dlkj_corr_free
double dlkj_corr_free(arma::vec x, int K, double eta, bool loglik);
RcppExport SEXP _spmirt_dlkj_corr_free(SEXP xSEXP, SEXP KSEXP, SEXP etaSEXP, SEXP loglikSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< bool >::type loglik(loglikSEXP);
    rcpp_result_gen = Rcpp::wrap(dlkj_corr_free(x, K, eta, loglik));
    return rcpp_result_gen;
END_RCPP
}
// testing
Rcpp::List testing(arma::mat X, arma::vec y);
RcppExport SEXP _spmirt_testing(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(testing(X, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _spmirt_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// matmatmat
arma::mat matmatmat(arma::mat x);
RcppExport SEXP _spmirt_matmatmat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(matmatmat(x));
    return rcpp_result_gen;
END_RCPP
}
// matmat
arma::mat matmat(arma::mat x);
RcppExport SEXP _spmirt_matmat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(matmat(x));
    return rcpp_result_gen;
END_RCPP
}
// ar_chol
arma::mat ar_chol(arma::mat x);
RcppExport SEXP _spmirt_ar_chol(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ar_chol(x));
    return rcpp_result_gen;
END_RCPP
}
// mat_inv
arma::mat mat_inv(arma::mat x);
RcppExport SEXP _spmirt_mat_inv(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_inv(x));
    return rcpp_result_gen;
END_RCPP
}
// mat_inv2
arma::mat mat_inv2(arma::mat x);
RcppExport SEXP _spmirt_mat_inv2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_inv2(x));
    return rcpp_result_gen;
END_RCPP
}
// inv_chol
arma::mat inv_chol(arma::mat x);
RcppExport SEXP _spmirt_inv_chol(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_chol(x));
    return rcpp_result_gen;
END_RCPP
}
// inv_solve
arma::mat inv_solve(arma::mat x, arma::mat eye);
RcppExport SEXP _spmirt_inv_solve(SEXP xSEXP, SEXP eyeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eye(eyeSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_solve(x, eye));
    return rcpp_result_gen;
END_RCPP
}
// inv_solve2
arma::mat inv_solve2(arma::mat x, arma::mat eye);
RcppExport SEXP _spmirt_inv_solve2(SEXP xSEXP, SEXP eyeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eye(eyeSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_solve2(x, eye));
    return rcpp_result_gen;
END_RCPP
}
// inv_form
arma::mat inv_form(arma::mat x, arma::mat eye);
RcppExport SEXP _spmirt_inv_form(SEXP xSEXP, SEXP eyeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eye(eyeSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_form(x, eye));
    return rcpp_result_gen;
END_RCPP
}
// rcpptn_hello_world
List rcpptn_hello_world();
RcppExport SEXP _spmirt_rcpptn_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpptn_hello_world());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _spmirt_vec2corr(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_spmirt_vec2mat", (DL_FUNC) &_spmirt_vec2mat, 3},
    {"_spmirt_vec2matt", (DL_FUNC) &_spmirt_vec2matt, 3},
    {"_spmirt_vecsub", (DL_FUNC) &_spmirt_vecsub, 3},
    {"_spmirt_vecsub1", (DL_FUNC) &_spmirt_vecsub1, 2},
    {"_spmirt_matsub1", (DL_FUNC) &_spmirt_matsub1, 3},
    {"_spmirt_subset_cpp", (DL_FUNC) &_spmirt_subset_cpp, 2},
    {"_spmirt_vec2trimatl", (DL_FUNC) &_spmirt_vec2trimatl, 3},
    {"_spmirt_trimatl2vec", (DL_FUNC) &_spmirt_trimatl2vec, 2},
    {"_spmirt_vec2chol_corr", (DL_FUNC) &_spmirt_vec2chol_corr, 2},
    {"_spmirt_chol_corr2vec", (DL_FUNC) &_spmirt_chol_corr2vec, 1},
    {"_spmirt_probit_gp_adap", (DL_FUNC) &_spmirt_probit_gp_adap, 5},
    {"_spmirt_probit_gp", (DL_FUNC) &_spmirt_probit_gp, 5},
    {"_spmirt_probit_gp_chol2", (DL_FUNC) &_spmirt_probit_gp_chol2, 5},
    {"_spmirt_probit_gp_chol", (DL_FUNC) &_spmirt_probit_gp_chol, 5},
    {"_spmirt_logit", (DL_FUNC) &_spmirt_logit, 1},
    {"_spmirt_logistic", (DL_FUNC) &_spmirt_logistic, 1},
    {"_spmirt_ifa_gibbs", (DL_FUNC) &_spmirt_ifa_gibbs, 5},
    {"_spmirt_ifa_gibbs_nonide", (DL_FUNC) &_spmirt_ifa_gibbs_nonide, 5},
    {"_spmirt_spifa_gibbs", (DL_FUNC) &_spmirt_spifa_gibbs, 5},
    {"_spmirt_multi_lm", (DL_FUNC) &_spmirt_multi_lm, 5},
    {"_spmirt_dmvnorm", (DL_FUNC) &_spmirt_dmvnorm, 3},
    {"_spmirt_dmvnorm_chol", (DL_FUNC) &_spmirt_dmvnorm_chol, 3},
    {"_spmirt_dmvnorm_cholinv", (DL_FUNC) &_spmirt_dmvnorm_cholinv, 3},
    {"_spmirt_dmvnorm_prec", (DL_FUNC) &_spmirt_dmvnorm_prec, 3},
    {"_spmirt_dinvwish", (DL_FUNC) &_spmirt_dinvwish, 3},
    {"_spmirt_dlkj_corr", (DL_FUNC) &_spmirt_dlkj_corr, 3},
    {"_spmirt_dlkj_corr_chol", (DL_FUNC) &_spmirt_dlkj_corr_chol, 3},
    {"_spmirt_dlkj_corr_free", (DL_FUNC) &_spmirt_dlkj_corr_free, 4},
    {"_spmirt_testing", (DL_FUNC) &_spmirt_testing, 2},
    {"_spmirt_rcpp_hello_world", (DL_FUNC) &_spmirt_rcpp_hello_world, 0},
    {"_spmirt_matmatmat", (DL_FUNC) &_spmirt_matmatmat, 1},
    {"_spmirt_matmat", (DL_FUNC) &_spmirt_matmat, 1},
    {"_spmirt_ar_chol", (DL_FUNC) &_spmirt_ar_chol, 1},
    {"_spmirt_mat_inv", (DL_FUNC) &_spmirt_mat_inv, 1},
    {"_spmirt_mat_inv2", (DL_FUNC) &_spmirt_mat_inv2, 1},
    {"_spmirt_inv_chol", (DL_FUNC) &_spmirt_inv_chol, 1},
    {"_spmirt_inv_solve", (DL_FUNC) &_spmirt_inv_solve, 2},
    {"_spmirt_inv_solve2", (DL_FUNC) &_spmirt_inv_solve2, 2},
    {"_spmirt_inv_form", (DL_FUNC) &_spmirt_inv_form, 2},
    {"_spmirt_rcpptn_hello_world", (DL_FUNC) &_spmirt_rcpptn_hello_world, 0},
    {"_spmirt_vec2corr",           (DL_FUNC) &_spmirt_vec2corr,           2},
    {NULL, NULL, 0}
};

RcppExport void R_init_spmirt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
