# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
vec2mat <- function(x, nrow, ncol) {
    .Call(`_spmirt_vec2mat`, x, nrow, ncol)
}

#' @export
vec2matt <- function(x, nrow, ncol) {
    .Call(`_spmirt_vec2matt`, x, nrow, ncol)
}

#' @export
vecsub <- function(x, first_index, n_length) {
    .Call(`_spmirt_vecsub`, x, first_index, n_length)
}

#' @export
vecsub1 <- function(x, index) {
    .Call(`_spmirt_vecsub1`, x, index)
}

#' @export
matsub1 <- function(x, index_row, index_col) {
    .Call(`_spmirt_matsub1`, x, index_row, index_col)
}

#' @export
subset_cpp <- function(X, y) {
    .Call(`_spmirt_subset_cpp`, X, y)
}

#' @title Spatial Probit Model
#'
#' @description
#' \code{ifa_gibbs} description.
#'
#' @details
#' details.
#'
#' @param par.
#'
#' @return return.
#'
#' @author Erick A. Chacon-Montalvan
#'
#' @examples
#'
#'
#' @export
probit_gp <- function(y, dist, params, iter) {
    .Call(`_spmirt_probit_gp`, y, dist, params, iter)
}

#' @export
dmvnorm <- function(x, mean, sigma) {
    .Call(`_spmirt_dmvnorm`, x, mean, sigma)
}

#' @export
testing <- function(X, y) {
    .Call(`_spmirt_testing`, X, y)
}

#' @export
logit <- function(p) {
    .Call(`_spmirt_logit`, p)
}

#' @export
logistic <- function(x) {
    .Call(`_spmirt_logistic`, x)
}

#' @title Bayesian item factor analysis
#'
#' @description
#' \code{ifa_gibbs} description.
#'
#' @details
#' details.
#'
#' @param par.
#'
#' @return return.
#'
#' @author Erick A. Chacon-Montalvan
#'
#' @examples
#' 
#'
#' @export
ifa_gibbs <- function(y, n, q, N, m = 1L) {
    .Call(`_spmirt_ifa_gibbs`, y, n, q, N, m)
}

#' @title Bayesian item factor analysis
#'
#' @description
#' \code{ifa_gibbs} description.
#'
#' @details
#' details.
#'
#' @param par.
#'
#' @return return.
#'
#' @author Erick A. Chacon-Montalvan
#'
#' @examples
#' 
#'
#' @export
ifa_gibbs_nonide <- function(y, n, q, N, m = 1L) {
    .Call(`_spmirt_ifa_gibbs_nonide`, y, n, q, N, m)
}

#' @title Spatial multidimesional item response model
#'
#' @description
#' \code{function} description.
#'
#' @details
#' details.
#'
#' @param par.
#'
#' @return return.
#'
#' @author Erick A. Chacon-Montalvan
#'
#' @examples
#' 
#'
#' @export
spifa_gibbs <- function(y, n, q, N, m = 1L) {
    .Call(`_spmirt_spifa_gibbs`, y, n, q, N, m)
}

#' @export
rcpp_hello_world <- function() {
    .Call(`_spmirt_rcpp_hello_world`)
}

#' @export
rcpptn_hello_world <- function() {
    .Call(`_spmirt_rcpptn_hello_world`)
}

