
# Block names are exactly the raw column-name prefixes generated by
# src/name-samples.cpp (e.g. "A[1,1]" -> "A", "c[3]" -> "c") -- no
# renaming, no case change. Case follows the C++ convention: matrices
# capitalized ("A", "Theta", "Z", "Chol", "Corr", "T", "B"), vectors
# lowercase ("c", "phi"). Used by as.list.spifa(), as_tibble.spifa(),
# and summary.spifa()'s `select`.
.spifa_var_blocks <- function (varnames) {
  gsub("\\[.+\\]", "", varnames)
}

#' @title Print a Fitted spifa Model
#'
#' @description
#' Concise summary of a fitted \code{spifa} object (the output of
#' \code{\link{spifa}}): model type, data dimensions, MCMC settings, and the
#' stored parameter blocks — rather than dumping every raw MCMC sample to the
#' console. Convert to a tidy tibble with \code{\link{as_tibble.spifa}} for
#' further inspection.
#'
#' @param x An object of class \code{spifa}, as returned by
#' \code{\link{spifa}}.
#' @param ... Further arguments passed to methods (currently unused).
#'
#' @return Invisibly returns \code{x}.
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' data(ipixuna)
#' samples <- spifa(items ~ 1, data = ipixuna, nfactors = 3, ngp = 0, niter = 20)
#' samples
#'
#' @export
print.spifa <- function (x, ...) {

  info <- attr(x, "fit_args")
  cat("<spifa model fit>\n")
  cat("Model type: ", info$model_type, "\n", sep = "")
  cat(info$nobs, " respondents, ", info$nitems, " items, ", info$nfactors,
      " factors\n", sep = "")
  if (is.list(x)) {
    cat(info$niter, " iterations requested (thin = ", info$thin,
        "); not executed (`execute = FALSE`)\n", sep = "")
  } else {
    varnames <- dimnames(x)[[3]]
    cat(info$niter, " iterations, thinned by ", info$thin, " (", dim(x)[1],
        " stored)\n", sep = "")
    cat("Parameter blocks: ", paste(unique(.spifa_var_blocks(varnames)), collapse = ", "),
        "\n", sep = "")
  }
  cat("Use as_tibble() for a tidy tibble, summary() for posterior summaries.\n")
  invisible(x)
}

#' @title Convert MCMC Samples to a Wide Tibble
#'
#' @description
#' Converts a fitted \code{spifa} object (the output of \code{\link{spifa}})
#' into a plain wide \code{\link[tibble]{tibble}}, with one column per
#' parameter and one row per (thinned, post-burnin) MCMC iteration. This is
#' a one-way export for use with \code{dplyr}/\code{ggplot2}/other tidyverse
#' tools directly — the package's own methods (\code{\link{summary.spifa}},
#' \code{\link{dic.spifa}}, \code{\link{predict.spifa}}) operate on the
#' fitted \code{spifa} object itself and do not need this conversion.
#'
#' @param x An object of class \code{spifa}, as returned by
#' \code{\link{spifa}}.
#' @param burnin Number of initial iterations to discard.
#' @param thin Thinning interval applied after discarding burn-in.
#' @param select Character vector of parameter blocks to keep (defaults to
#' all of them).
#' @param ... Further arguments passed to methods (currently unused; present
#' for consistency with the \code{\link[tibble]{as_tibble}} generic).
#'
#' @return A plain wide \code{\link[tibble]{tibble}}, with the
#' \code{"fit_args"} attribute carried over from \code{x}.
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' data(ipixuna)
#' nitems <- ncol(ipixuna$items)
#' nfactors <- 3
#'
#' # discrimination constraint: start with every item free to load on every
#' # factor, then restrict a few items per factor based on what each item is
#' # meant to measure (0 = no relationship, 1 = free parameter to estimate)
#' A <- matrix(1, nitems, nfactors)
#' A[c(4, 8), 1] <- 0
#' A[c(2, 4, 5, 6, 7, 8, 10), 2] <- 0
#' A[c(5, 6), 3] <- 0
#' samples <- spifa(
#'   items ~ 1, data = ipixuna, nfactors = nfactors, ngp = 0,
#'   niter = 20, standardize = FALSE,
#'   constraints = list(discrimination = A))
#' samples_tib <- as_tibble(samples)
#' samples_tib
#' }
#'
#' @importFrom tibble as_tibble
#'
#' @export
as_tibble.spifa <- function (x, burnin = 0, thin = 1, select = NULL, ...) {

  fit_args <- attr(x, "fit_args")
  varnames <- dimnames(x)[[3]]
  if (!is.null(select)) {
    idx <- .spifa_var_blocks(varnames) %in% select
    x <- x[, , idx, drop = FALSE]
    varnames <- varnames[idx]
  }
  niter <- dim(x)[1]
  mat <- matrix(x[, 1, ], nrow = niter, ncol = length(varnames),
                dimnames = list(NULL, varnames))
  df <- tibble::as_tibble(mat)
  df <- df[seq(burnin + 1, niter, thin), ]
  attr(df, "fit_args") <- fit_args
  return(df)
}

#' @title Convert a Fitted spifa Model to a spifa.list
#'
#' @description
#' Splits a fitted \code{spifa} object back into a named list of matrices,
#' one per parameter block (e.g. \code{c}, \code{a}, \code{theta}, ...).
#' Used internally by \code{\link{predict.spifa}} and \code{\link{dic.spifa}},
#' which need matrix-shaped samples to pass to their C++ counterparts.
#'
#' @param x An object of class \code{spifa}, as returned by
#' \code{\link{spifa}}.
#' @param ... Further arguments passed to methods (currently unused).
#'
#' @return An object of class \code{spifa.list}: a named list of matrices,
#' one per parameter block, with the \code{"fit_args"} attribute carried
#' over from \code{x}.
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' data(ipixuna)
#' nitems <- ncol(ipixuna$items)
#' nfactors <- 3
#'
#' # discrimination constraint: start with every item free to load on every
#' # factor, then restrict a few items per factor based on what each item is
#' # meant to measure (0 = no relationship, 1 = free parameter to estimate)
#' A <- matrix(1, nitems, nfactors)
#' A[c(4, 8), 1] <- 0
#' A[c(2, 4, 5, 6, 7, 8, 10), 2] <- 0
#' A[c(5, 6), 3] <- 0
#' samples <- spifa(
#'   items ~ 1, data = ipixuna, nfactors = nfactors, ngp = 0,
#'   niter = 20, standardize = FALSE,
#'   constraints = list(discrimination = A))
#' samples_list <- as.list(samples)
#' names(samples_list)
#' }
#'
#' @export
as.list.spifa <- function (x, ...) {

  fit_args <- attr(x, "fit_args")
  varnames <- dimnames(x)[[3]]
  niter <- dim(x)[1]
  blocks <- .spifa_var_blocks(varnames)
  block_names_unique <- unique(blocks)

  extract_block <- function (block) {
    idx <- which(blocks == block)
    matrix(x[, 1, idx], nrow = niter, ncol = length(idx),
           dimnames = list(NULL, varnames[idx]))
  }

  samples <- lapply(block_names_unique, extract_block)
  names(samples) <- block_names_unique
  class(samples) <- c("spifa.list", class(samples))
  attr(samples, "fit_args") <- fit_args
  attr(samples, "predict_setup") <- attr(x, "predict_setup")
  return(samples)
}

#' @title Gather Parameters into a Long Format Tibble
#'
#' @description
#' Reshapes a wide samples tibble (one column per parameter, as produced by
#' \code{\link{as_tibble.spifa}}) into long format (one row per
#' iteration/parameter pair), which is the shape expected by the
#' \code{\link{gg_trace}}/\code{\link{gg_density}} family of plotting
#' helpers.
#'
#' @param samples_wide A wide samples tibble, e.g. from
#' \code{\link{as_tibble.spifa}}.
#' @param each If not \code{NULL}, the number of columns that make up each
#' group of parameters (e.g. the number of items), used to additionally
#' split the gathered \code{Parameters} column into \code{group}/
#' \code{Parameter} columns.
#' @param keys Names to use for the group/parameter columns when \code{each}
#' is supplied.
#'
#' @return A long-format \code{\link[tibble]{tibble}} with columns
#' \code{iteration}, \code{Parameters}, and \code{Value} (plus \code{group}/
#' the second \code{keys} element when \code{each} is supplied).
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' data(ipixuna)
#' nitems <- ncol(ipixuna$items)
#' nfactors <- 3
#'
#' # discrimination constraint: start with every item free to load on every
#' # factor, then restrict a few items per factor based on what each item is
#' # meant to measure (0 = no relationship, 1 = free parameter to estimate)
#' A <- matrix(1, nitems, nfactors)
#' A[c(4, 8), 1] <- 0
#' A[c(2, 4, 5, 6, 7, 8, 10), 2] <- 0
#' A[c(5, 6), 3] <- 0
#' samples <- spifa(
#'   items ~ 1, data = ipixuna, nfactors = nfactors, ngp = 0,
#'   niter = 20, standardize = FALSE,
#'   constraints = list(discrimination = A))
#' wide <- as_tibble(samples, select = "c")
#' long <- gather.spifa(wide)
#' long
#' }
#'
#' @export
gather.spifa <- function (samples_wide, each = NULL,
                           keys = c("group", "Parameter")) {

  # Convert to long format
  samples_long <- samples_wide |>
    tibble::as_tibble() |>
    dplyr::mutate(iteration = 1:dplyr::n()) |>
    tidyr::gather(Parameters, Value, -iteration, factor_key = TRUE)

  if (!is.null(each)) {

    # Auxiliary variables to group
    groups <- paste0(keys[1], rep(1:each, ncol(samples_wide)/each))
    groups <- factor(groups, unique(groups))
    var <- paste0(keys[2], rep(1:(ncol(samples_wide)/each), each = each))
    names(groups) <- levels(samples_long$Parameters)
    names(var) <- levels(samples_long$Parameters)

    # Group parameters
    samples_long <- samples_long |>
      dplyr::mutate(groups = groups[Parameters], var = var[Parameters]) |>
    dplyr::select(-Parameters) |>
    tidyr::spread(var, Value)

  }

  return(samples_long)
}


#' @title Posterior Summary of MCMC Samples
#'
#' @description
#' Computes posterior summary statistics for every parameter in a fitted
#' \code{spifa} object, via \code{\link[posterior]{summarise_draws}}: mean,
#' median, sd, mad, the 2.5\%/10\%/50\%/90\%/97.5\% quantiles, and effective
#' sample size (bulk and tail). \code{rhat} is not included since
#' \code{\link{spifa}} only ever fits a single chain.
#'
#' @param object A fitted \code{spifa} object, as returned by
#' \code{\link{spifa}}.
#' @param burnin Number of initial iterations to discard.
#' @param thin Thinning interval applied after discarding burn-in.
#' @param select Character vector of parameter blocks to summarise (defaults
#' to all of them).
#' @param ... Further arguments passed to methods (currently unused).
#'
#' @return A \code{\link[tibble]{tibble}} with one row per parameter; see
#' \code{\link[posterior]{summarise_draws}} for column details.
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' data(ipixuna)
#' nitems <- ncol(ipixuna$items)
#' nfactors <- 3
#'
#' # discrimination constraint: start with every item free to load on every
#' # factor, then restrict a few items per factor based on what each item is
#' # meant to measure (0 = no relationship, 1 = free parameter to estimate)
#' A <- matrix(1, nitems, nfactors)
#' A[c(4, 8), 1] <- 0
#' A[c(2, 4, 5, 6, 7, 8, 10), 2] <- 0
#' A[c(5, 6), 3] <- 0
#' samples <- spifa(
#'   items ~ 1, data = ipixuna, nfactors = nfactors, ngp = 0,
#'   niter = 20, standardize = FALSE,
#'   constraints = list(discrimination = A))
#' summary(samples, select = "c")
#' }
#'
#' @export
summary.spifa <- function (object, burnin = 0, thin = 1, select = NULL, ...) {

  niter <- dim(object)[1]
  object <- object[seq(burnin + 1, niter, thin), , , drop = FALSE]
  if (!is.null(select)) {
    varnames <- dimnames(object)[[3]]
    idx <- .spifa_var_blocks(varnames) %in% select
    object <- object[, , idx, drop = FALSE]
  }
  posterior::summarise_draws(object, "mean", "median", "sd", "mad",
    ~posterior::quantile2(.x, probs = c(0.025, 0.1, 0.5, 0.9, 0.975)),
    "ess_bulk", "ess_tail")
}

#' @title Deviance Information Criterion
#'
#' @description
#' Generic function for the Deviance Information Criterion (DIC), a
#' Bayesian measure of model fit that penalises complexity. See
#' \code{\link{dic.spifa}} for the \code{spifa} method.
#'
#' @param x A fitted model object.
#' @param ... Further arguments passed to methods.
#'
#' @export
dic <- function (x, ...) {
  UseMethod("dic", x)
}


#' @title Deviance Information Criterion for a spifa Model
#'
#' @description
#' Computes the Deviance Information Criterion (DIC) for a fitted
#' \code{spifa} model, useful for comparing candidate models (e.g. different
#' numbers of factors or different restriction structures) fitted to the
#' same data.
#'
#' @param x A fitted \code{spifa} object, as returned by \code{\link{spifa}}.
#' @param ... Further arguments passed to methods (currently unused).
#'
#' @return A list with elements \code{average_of_deviance},
#' \code{n_effec_params} (effective number of parameters), and \code{dic}.
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' data(ipixuna)
#' nitems <- ncol(ipixuna$items)
#' nfactors <- 3
#'
#' # discrimination constraint: start with every item free to load on every
#' # factor, then restrict a few items per factor based on what each item is
#' # meant to measure (0 = no relationship, 1 = free parameter to estimate)
#' A <- matrix(1, nitems, nfactors)
#' A[c(4, 8), 1] <- 0
#' A[c(2, 4, 5, 6, 7, 8, 10), 2] <- 0
#' A[c(5, 6), 3] <- 0
#' samples <- spifa(
#'   items ~ 1, data = ipixuna, nfactors = nfactors, ngp = 0,
#'   niter = 20, standardize = FALSE,
#'   constraints = list(discrimination = A))
#' dic(samples)
#' }
#'
#' @export
dic.spifa <- function (x, ...) {

  object <- x
  # convert to spifa.list
  samples <- as.list(object)

  # DIC calling c++ dic_cpp
  dic <- dic_cpp(y = attr(object, "fit_args")$response, c = samples$c,
                 a = samples$A, theta = samples$Theta,
                 n = attr(object, "fit_args")$nobs,
                 q = attr(object, "fit_args")$nitems,
                 m = attr(object, "fit_args")$nfactors,
                 L = attr(object, "fit_args")$constrain_L)

  return(dic)
}

#' @title Predict from a Fitted spifa Model
#'
#' @description
#' Predicts the latent factors of (spatial) item factor analysis
#' for new subjects/locations and/or for new predictor values, using
#' the posterior samples from a fitted \code{\link{spifa}} model.
#'
#' @details
#' If the fitted model has no spatial or predictor structure (\code{eifa} or
#' \code{cifa}), or if \code{newdata} is not supplied for a model that has
#' one, there is nothing to predict beyond the latent abilities' own
#' posterior samples already available from the fit, so those are returned
#' directly (subject to \code{burnin}/\code{thin}) instead of calling the
#' \code{C++} sampler. Otherwise, prediction for the new locations and/or
#' predictor values is delegated to the \code{C++} sampler.
#'
#' If the fitted model has predictors (\code{cifa_pred}/\code{spifa_pred}),
#' \code{newdata} must include those predictor columns, the same as
#' \code{\link[stats]{predict.lm}} and similar methods require -- this is
#' an error otherwise. There's no synthesized reference-level fallback for
#' missing predictors (e.g. an \code{sf}/\code{sfc} object holding only new
#' locations, with no predictor columns at all): for a factor predictor
#' under the no-intercept encoding \code{\link{spifa}} uses, an
#' automatically-filled all-zero row wouldn't correspond to any real
#' category, so any reference profile -- including all zeros for numeric
#' predictors -- must be supplied explicitly in \code{newdata}, matching
#' the original data's format.
#'
#' @param object A fitted \code{spifa} object, as returned by
#' \code{\link{spifa}}.
#' @param newdata New data to predict at, mirroring \code{\link{spifa}}'s
#' own \code{data} argument: an \code{\link[sf]{sf}}/\code{\link[sf]{sfc}}
#' object (for spatial, i.e. \code{spifa}/\code{spifa_pred}, models --
#' its geometry gives the new locations, and its CRS is used directly, so
#' it need not match the training data's CRS) or a plain data frame (for
#' \code{cifa_pred}), with columns matching the predictors used on the
#' right-hand side of \code{formula} when the model was fitted. Its design
#' matrix is built the same way \code{\link{spifa}} built the training one,
#' using the same terms and factor levels.
#' @param burnin Number of initial (post-fitting) iterations to discard
#' before using the posterior samples for prediction.
#' @param thin Thinning interval applied to the posterior samples used for
#' prediction.
#' @param joint Logical; for spatial models (\code{spifa}/\code{spifa_pred}),
#' whether the posterior predictive draws should respect the full predictive
#' covariance across new locations and factors (\code{TRUE}), or be drawn
#' marginally/independently per location-factor combination (\code{FALSE},
#' the default, cheaper). Each draw still propagates posterior parameter
#' uncertainty (one draw per retained MCMC iteration) either way -- this
#' only controls whether, within a single draw, the values across new
#' locations/factors are jointly correlated as the model implies. Marginal
#' draws are fine for per-location summaries (e.g. means, credible
#' intervals computed independently per column); set \code{TRUE} when the
#' samples themselves will be used as input to another model or computation
#' that depends on their joint structure (e.g. a spatial contrast or
#' aggregate across new locations). Ignored for \code{cifa_pred}, whose
#' draws are already jointly correct across factors.
#' @param ... Further arguments (currently unused).
#'
#' @return A \code{\link[posterior]{draws_array}} of posterior predictive
#' samples of the latent abilities (\code{theta}) for the requested new
#' locations and/or predictor values (or, if no prediction was requested,
#' for the originally observed subjects).
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' library(sf)
#' data(ipixuna)
#'
#' nitems <- ncol(ipixuna$items)
#' nfactors <- 3
#' A <- matrix(1, nitems, nfactors)
#' A[c(4, 8), 1] <- 0
#' A[c(2, 4, 5, 6, 7, 8, 10), 2] <- 0
#' A[c(5, 6), 3] <- 0
#'
#' # Spifa model
#' samples <- spifa(items ~ 1, data = ipixuna, nfactors = nfactors, niter = 5,
#'   constraints = list(discrimination = A))
#' # latent abilities for observed locations
#' predict(samples)
#' # latent abilities for new locations
#' newdata <- st_make_grid(ipixuna, n = c(3, 2), what = "centers")
#' predict(samples, newdata = newdata)
#'
#' # Spifa model with predictors
#' samples_pred <- spifa(items ~ wealth, data = ipixuna, nfactors = nfactors, niter = 5,
#'   constraints = list(discrimination = A))
#' newdata_pred <- st_sf(wealth = rnorm(6), geometry = newdata)
#' predict(samples_pred, newdata = newdata_pred)
#' }
#'
#' @export
predict.spifa <- function (object, newdata = NULL, burnin = 0, thin = 1,
                                joint = FALSE, ...) {

  fit_args <- attr(object, "fit_args")
  predict_setup <- attr(object, "predict_setup")

  # Filter to the posterior samples and convert to list
  idx <- seq(burnin + 1, nrow(object), thin)
  object <- posterior::subset_draws(object, iteration = idx)
  object <- as.list(object)

  # Prediction I: for the observed subjects/locations
  has_newcoords <- inherits(newdata, "sf") || inherits(newdata, "sfc")
  if (fit_args$model_type %in% c("eifa", "cifa") |
      (fit_args$model_type == "cifa_pred" & is.null(newdata)) |
      (fit_args$model_type == "spifa" & !has_newcoords) |
      (fit_args$model_type == "spifa_pred" & is.null(newdata))) {
    return(posterior::as_draws_array(object$Theta))
  }

  # Prediction II: for the new subjects/locations
  coordinates <- predict_setup$coordinates
  pred_terms <- predict_setup$pred_terms

  # Construct distances for spifa/spifa_pred
  if (fit_args$model_type == "cifa_pred") {
    npred <- nrow(newdata)
    newdist <- matrix(nrow = 0, ncol = 0)
    cross_distances <- matrix(nrow = 0, ncol = 0)
  } else {
    if (!has_newcoords) {
      stop("newdata must be an sf/sfc object for a spatial model.", call. = FALSE)
    }
    newcoords <- sf::st_geometry(newdata)
    npred <- length(newcoords)
    newdist <- matrix(as.numeric(sf::st_distance(newcoords)), npred, npred)
    cross_distances <- matrix(as.numeric(sf::st_distance(newcoords, coordinates)),
      npred, length(coordinates))
  }

  # Contruct newpredictors
  if (fit_args$model_type %in% c("cifa_pred", "spifa_pred") &&
      !all(all.vars(pred_terms) %in% names(newdata))) {
    stop("newdata is missing the predictor column(s) required (",
      paste(all.vars(pred_terms), collapse = ", "), ").", call. = FALSE)
  } else if (fit_args$model_type == "spifa") {
    newpredictors <- matrix(nrow = npred, ncol = 0)
  } else {
    mf_new <- model.frame(pred_terms, newdata, xlev = predict_setup$xlevels)
    newpredictors <- model.matrix(pred_terms, mf_new)
  }

  # List of options to call c++ function to predict
  as_pred_mat <- function (block) {
    if (is.null(object[[block]])) matrix(nrow = 0, ncol = length(idx)) else t(object[[block]])
  }
  predict_args <- list(samples_theta = t(object$Theta),
    samples_corr_chol = t(object$Chol), samples_corr = t(object$Corr),
    samples_mgp_sd = as_pred_mat("T"), samples_mgp_phi = as_pred_mat("phi"),
    samples_betas = as_pred_mat("B"),
    response = fit_args$response, predictors = fit_args$predictors, newpredictors = newpredictors,
    distances = fit_args$distances, newdist = newdist, cross_distances = cross_distances,
    nobs = fit_args$nobs, nitems = fit_args$nitems, nfactors = fit_args$nfactors, ngp = fit_args$ngp,
    npred = npred, niter = length(idx), burnin = 0, thin = 1,
    constrain_L = fit_args$constrain_L, constrain_T = fit_args$constrain_T,
    constrain_V_sd = fit_args$constrain_V_sd,
    model_type = fit_args$model_type, joint = joint
    )

  # Predict calling c++ predict_cpp
  prediction <- do.call(predict_cpp, predict_args)

  return(posterior::as_draws_array(prediction$theta))
}
