
# Raw column-name prefixes (as generated by src/name-samples.cpp, e.g.
# "A[1,1]", "T[2,2]") mapped to the block/argument names used throughout the
# R API (e.g. "discrimination"'s samples are internally "a", the GP standard
# deviation block is internally named "T" in C++ but "mgp_sd" in R). Shared
# by as_list.spifa(), as_tibble.spifa(), and summary.spifa()'s `select`.
.spifa_pars <- c("c", "a", "theta", "z", "corr_chol", "corr", "mgp_sd", "mgp_phi", "betas")
names(.spifa_pars) <- c("c", "A", "Theta", "Z", "Corr_chol", "Corr", "T", "mgp_phi", "B")

.spifa_var_blocks <- function (varnames) {
  raw <- gsub("\\[.+\\]", "", varnames)
  unname(.spifa_pars[raw])
}

#' @title Print a Fitted spifa Model
#'
#' @description
#' Concise summary of a fitted \code{spifa} object (the output of
#' \code{\link{spifa}}): model type, data dimensions, MCMC settings, and the
#' stored parameter blocks — rather than dumping every raw MCMC sample to the
#' console. Convert to a tidy tibble with \code{\link{as_tibble.spifa}} for
#' further inspection.
#'
#' @param x An object of class \code{spifa}, as returned by
#' \code{\link{spifa}}.
#' @param ... Further arguments passed to methods (currently unused).
#'
#' @return Invisibly returns \code{x}.
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' data(ipixuna)
#' ipixuna_wide$items <- as.matrix(dplyr::select(ipixuna_wide, `Item 1`:`Item 10`))
#' samples <- spifa(items ~ 1, data = ipixuna_wide, nfactors = 2, niter = 20, thin = 1)
#' samples
#'
#' @export
print.spifa <- function (x, ...) {

  info <- attr(x, "model_info")
  cat("<spifa model fit>\n")
  cat("Model type: ", info$model_type, "\n", sep = "")
  cat(info$nobs, " respondents, ", info$nitems, " items, ", info$nfactors,
      " factors\n", sep = "")
  if (is.list(x)) {
    cat(info$niter, " iterations requested (thin = ", info$thin,
        "); not executed (`execute = FALSE`)\n", sep = "")
  } else {
    varnames <- dimnames(x)[[3]]
    cat(info$niter, " iterations, thinned by ", info$thin, " (", dim(x)[1],
        " stored)\n", sep = "")
    cat("Parameter blocks: ", paste(unique(.spifa_var_blocks(varnames)), collapse = ", "),
        "\n", sep = "")
  }
  cat("Use as_tibble() for a tidy tibble, summary() for posterior summaries.\n")
  invisible(x)
}

#' @title Convert MCMC Samples to a Wide Tibble
#'
#' @description
#' Converts a fitted \code{spifa} object (the output of \code{\link{spifa}})
#' into a plain wide \code{\link[tibble]{tibble}}, with one column per
#' parameter and one row per (thinned, post-burnin) MCMC iteration. This is
#' a one-way export for use with \code{dplyr}/\code{ggplot2}/other tidyverse
#' tools directly — the package's own methods (\code{\link{summary.spifa}},
#' \code{\link{dic.spifa}}, \code{\link{predict.spifa}}) operate on the
#' fitted \code{spifa} object itself and do not need this conversion.
#'
#' @param x An object of class \code{spifa}, as returned by
#' \code{\link{spifa}}.
#' @param burnin Number of initial iterations to discard.
#' @param thin Thinning interval applied after discarding burn-in.
#' @param select Character vector of parameter blocks to keep (defaults to
#' all of them).
#' @param ... Further arguments passed to methods (currently unused; present
#' for consistency with the \code{\link[tibble]{as_tibble}} generic).
#'
#' @return A plain wide \code{\link[tibble]{tibble}}, with the
#' \code{"model_info"} attribute carried over from \code{x}.
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' data(ipixuna)
#' parameters <- attr(ipixuna_wide, "parameters")
#' L_a <- (parameters$discrimination != 0) * 1
#' ipixuna_wide$items <- as.matrix(dplyr::select(ipixuna_wide, `Item 1`:`Item 10`))
#' samples <- spifa(
#'   items ~ 1, data = ipixuna_wide, nfactors = 2,
#'   niter = 20, thin = 1, standardize = FALSE,
#'   constraints = list(discrimination = L_a, mgp = diag(2), resid_sd = rep(0.5, 2)))
#' samples_tib <- as_tibble(samples)
#' samples_tib
#' }
#'
#' @importFrom tibble as_tibble
#'
#' @export
as_tibble.spifa <- function (x, burnin = 0, thin = 1, select = NULL, ...) {

  model_info <- attr(x, "model_info")
  varnames <- dimnames(x)[[3]]
  if (!is.null(select)) {
    idx <- .spifa_var_blocks(varnames) %in% select
    x <- x[, , idx, drop = FALSE]
    varnames <- varnames[idx]
  }
  niter <- dim(x)[1]
  mat <- matrix(x[, 1, ], nrow = niter, ncol = length(varnames),
                dimnames = list(NULL, varnames))
  df <- tibble::as_tibble(mat)
  df <- df[seq(burnin + 1, niter, thin), ]
  attr(df, "model_info") <- model_info
  return(df)
}

#' @title Convert Samples to a spifa.list
#'
#' @description
#' Generic function converting posterior samples back into the
#' \code{spifa.list} representation (one matrix per parameter block). See
#' \code{\link{as_list.spifa}} for the \code{spifa} method.
#'
#' @param x An object to convert.
#' @param ... Further arguments passed to methods.
#'
#' @export
as_list <- function (x, ...) {
  UseMethod("as_list", x)
}

#' @title Convert a Fitted spifa Model to a spifa.list
#'
#' @description
#' Splits a fitted \code{spifa} object back into a named list of matrices,
#' one per parameter block (e.g. \code{c}, \code{a}, \code{theta}, ...).
#' Used internally by \code{\link{predict.spifa}} and \code{\link{dic.spifa}},
#' which need matrix-shaped samples to pass to their C++ counterparts.
#'
#' @param x An object of class \code{spifa}, as returned by
#' \code{\link{spifa}}.
#' @param ... Further arguments passed to methods (currently unused).
#'
#' @return An object of class \code{spifa.list}: a named list of matrices,
#' one per parameter block, with the \code{"model_info"} attribute carried
#' over from \code{x}.
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' data(ipixuna)
#' parameters <- attr(ipixuna_wide, "parameters")
#' L_a <- (parameters$discrimination != 0) * 1
#' ipixuna_wide$items <- as.matrix(dplyr::select(ipixuna_wide, `Item 1`:`Item 10`))
#' samples <- spifa(
#'   items ~ 1, data = ipixuna_wide, nfactors = 2,
#'   niter = 20, thin = 1, standardize = FALSE,
#'   constraints = list(discrimination = L_a, mgp = diag(2), resid_sd = rep(0.5, 2)))
#' samples_list <- as_list(samples)
#' names(samples_list)
#' }
#'
#' @export
as_list.spifa <- function (x, ...) {

  model_info <- attr(x, "model_info")
  varnames <- dimnames(x)[[3]]
  niter <- dim(x)[1]
  blocks <- .spifa_var_blocks(varnames)
  block_names_unique <- unique(blocks)

  extract_block <- function (block) {
    idx <- which(blocks == block)
    matrix(x[, 1, idx], nrow = niter, ncol = length(idx),
           dimnames = list(NULL, varnames[idx]))
  }

  samples <- lapply(block_names_unique, extract_block)
  names(samples) <- block_names_unique
  class(samples) <- c("spifa.list", class(samples))
  attr(samples, "model_info") <- model_info
  return(samples)
}

#' @title Gather Parameters into a Long Format Tibble
#'
#' @description
#' Reshapes a wide samples tibble (one column per parameter, as produced by
#' \code{\link{as_tibble.spifa}}) into long format (one row per
#' iteration/parameter pair), which is the shape expected by the
#' \code{\link{gg_trace}}/\code{\link{gg_density}} family of plotting
#' helpers.
#'
#' @param samples_wide A wide samples tibble, e.g. from
#' \code{\link{as_tibble.spifa}}.
#' @param each If not \code{NULL}, the number of columns that make up each
#' group of parameters (e.g. the number of items), used to additionally
#' split the gathered \code{Parameters} column into \code{group}/
#' \code{Parameter} columns.
#' @param keys Names to use for the group/parameter columns when \code{each}
#' is supplied.
#'
#' @return A long-format \code{\link[tibble]{tibble}} with columns
#' \code{iteration}, \code{Parameters}, and \code{Value} (plus \code{group}/
#' the second \code{keys} element when \code{each} is supplied).
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' data(ipixuna)
#' parameters <- attr(ipixuna_wide, "parameters")
#' L_a <- (parameters$discrimination != 0) * 1
#' ipixuna_wide$items <- as.matrix(dplyr::select(ipixuna_wide, `Item 1`:`Item 10`))
#' samples <- spifa(
#'   items ~ 1, data = ipixuna_wide, nfactors = 2,
#'   niter = 20, thin = 1, standardize = FALSE,
#'   constraints = list(discrimination = L_a, mgp = diag(2), resid_sd = rep(0.5, 2)))
#' wide <- as_tibble(samples, select = "c")
#' long <- gather.spifa(wide)
#' long
#' }
#'
#' @export
gather.spifa <- function (samples_wide, each = NULL,
                           keys = c("group", "Parameter")) {

  # Convert to long format
  samples_long <- samples_wide %>%
    tibble::as_tibble() %>%
    dplyr::mutate(iteration = 1:dplyr::n()) %>%
    tidyr::gather(Parameters, Value, -iteration, factor_key = TRUE)

  if (!is.null(each)) {

    # Auxiliary variables to group
    groups <- paste0(keys[1], rep(1:each, ncol(samples_wide)/each))
    groups <- factor(groups, unique(groups))
    var <- paste0(keys[2], rep(1:(ncol(samples_wide)/each), each = each))
    names(groups) <- levels(samples_long$Parameters)
    names(var) <- levels(samples_long$Parameters)

    # Group parameters
    samples_long <- samples_long %>%
      dplyr::mutate(groups = groups[Parameters], var = var[Parameters]) %>%
    dplyr::select(-Parameters) %>%
    tidyr::spread(var, Value)

  }

  return(samples_long)
}


#' @title Posterior Summary of MCMC Samples
#'
#' @description
#' Computes posterior summary statistics for every parameter in a fitted
#' \code{spifa} object, via \code{\link[posterior]{summarise_draws}}: mean,
#' median, sd, mad, the 2.5\%/10\%/50\%/90\%/97.5\% quantiles, and effective
#' sample size (bulk and tail). \code{rhat} is not included since
#' \code{\link{spifa}} only ever fits a single chain.
#'
#' @param object A fitted \code{spifa} object, as returned by
#' \code{\link{spifa}}.
#' @param burnin Number of initial iterations to discard.
#' @param thin Thinning interval applied after discarding burn-in.
#' @param select Character vector of parameter blocks to summarise (defaults
#' to all of them).
#' @param ... Further arguments passed to methods (currently unused).
#'
#' @return A \code{\link[tibble]{tibble}} with one row per parameter; see
#' \code{\link[posterior]{summarise_draws}} for column details.
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' data(ipixuna)
#' parameters <- attr(ipixuna_wide, "parameters")
#' L_a <- (parameters$discrimination != 0) * 1
#' ipixuna_wide$items <- as.matrix(dplyr::select(ipixuna_wide, `Item 1`:`Item 10`))
#' samples <- spifa(
#'   items ~ 1, data = ipixuna_wide, nfactors = 2,
#'   niter = 20, thin = 1, standardize = FALSE,
#'   constraints = list(discrimination = L_a, mgp = diag(2), resid_sd = rep(0.5, 2)))
#' summary(samples, select = "c")
#' }
#'
#' @export
summary.spifa <- function (object, burnin = 0, thin = 1, select = NULL, ...) {

  niter <- dim(object)[1]
  object <- object[seq(burnin + 1, niter, thin), , , drop = FALSE]
  if (!is.null(select)) {
    varnames <- dimnames(object)[[3]]
    idx <- .spifa_var_blocks(varnames) %in% select
    object <- object[, , idx, drop = FALSE]
  }
  posterior::summarise_draws(object, "mean", "median", "sd", "mad",
    ~posterior::quantile2(.x, probs = c(0.025, 0.1, 0.5, 0.9, 0.975)),
    "ess_bulk", "ess_tail")
}

#' @title Deviance Information Criterion
#'
#' @description
#' Generic function for the Deviance Information Criterion (DIC), a
#' Bayesian measure of model fit that penalises complexity. See
#' \code{\link{dic.spifa}} for the \code{spifa} method.
#'
#' @param x A fitted model object.
#' @param ... Further arguments passed to methods.
#'
#' @export
dic <- function (x, ...) {
  UseMethod("dic", x)
}


#' @title Deviance Information Criterion for a spifa Model
#'
#' @description
#' Computes the Deviance Information Criterion (DIC) for a fitted
#' \code{spifa} model, useful for comparing candidate models (e.g. different
#' numbers of factors or different restriction structures) fitted to the
#' same data.
#'
#' @param x A fitted \code{spifa} object, as returned by \code{\link{spifa}}.
#' @param ... Further arguments passed to methods (currently unused).
#'
#' @return A list with elements \code{average_of_deviance},
#' \code{n_effec_params} (effective number of parameters), and \code{dic}.
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' data(ipixuna)
#' parameters <- attr(ipixuna_wide, "parameters")
#' L_a <- (parameters$discrimination != 0) * 1
#' ipixuna_wide$items <- as.matrix(dplyr::select(ipixuna_wide, `Item 1`:`Item 10`))
#' samples <- spifa(
#'   items ~ 1, data = ipixuna_wide, nfactors = 2,
#'   niter = 20, thin = 1, standardize = FALSE,
#'   constraints = list(discrimination = L_a, mgp = diag(2), resid_sd = rep(0.5, 2)))
#' dic(samples)
#' }
#'
#' @export
dic.spifa <- function (x, ...) {

  object <- x
  # convert to spifa.list
  samples <- as_list(object)

  # DIC calling c++ dic_cpp
  dic <- dic_cpp(y = attr(object, "model_info")$response, c = samples$c,
                 a = samples$a, theta = samples$theta,
                 n = attr(object, "model_info")$nobs,
                 q = attr(object, "model_info")$nitems,
                 m = attr(object, "model_info")$nfactors,
                 L = attr(object, "model_info")$constrain_L)

  return(dic)
}

#' @title Predict from a Fitted spifa Model
#'
#' @description
#' Predicts the latent factors (and, for spatial models, the underlying
#' spatial process) at new locations and/or for new predictor values, using
#' the posterior samples from a fitted \code{\link{spifa}} model.
#'
#' @details
#' If the fitted model has no spatial or predictor structure (\code{eifa} or
#' \code{cifa}), or if neither \code{newcoords} nor \code{newdata} is
#' supplied for a model that has one, there is nothing to predict beyond the
#' posterior means of the latent abilities already available from the fitted
#' samples, and the function currently returns early. Otherwise, prediction
#' for the new locations and/or predictor values is delegated to the
#' \code{C++} sampler.
#'
#' @param object A fitted \code{spifa} object, as returned by
#' \code{\link{spifa}}.
#' @param newdata New values of the predictors used on the right-hand side
#' of \code{formula} when the model was fitted (only needed for models
#' with predictors).
#' @param newcoords New spatial coordinates to predict at (only needed for
#' spatial, i.e. \code{spifa}/\code{spifa_pred}, models).
#' @param burnin Number of initial (post-fitting) iterations to discard
#' before using the posterior samples for prediction.
#' @param thin Thinning interval applied to the posterior samples used for
#' prediction.
#' @param se.fit Currently unused; reserved for returning prediction
#' standard errors.
#' @param ... Further arguments (currently unused).
#'
#' @return A list of posterior predictive samples/summaries for the
#' requested new locations and/or predictor values.
#'
#' @author Erick A. Chacón-Montalván
#'
#' @examples
#' \donttest{
#' data(ipixuna)
#' parameters <- attr(ipixuna_wide, "parameters")
#' L_a <- (parameters$discrimination != 0) * 1
#' ipixuna_sf <- sf::st_as_sf(ipixuna_wide)
#' ipixuna_sf$items <- as.matrix(dplyr::select(ipixuna_wide, `Item 1`:`Item 10`))
#' samples <- spifa(
#'   items ~ 1, data = ipixuna_sf,
#'   nfactors = 2, niter = 5, thin = 1, standardize = FALSE,
#'   constraints = list(discrimination = L_a, mgp = diag(2), resid_sd = rep(0.5, 2)))
#' newcoords <- sf::st_coordinates(ipixuna_wide$coords)[1:5, , drop = FALSE]
#' predict(samples, newcoords = newcoords)
#' }
#'
#' @export
predict.spifa <- function (object, newdata = NULL, newcoords = NULL, burnin = 0,
                                thin = 1, se.fit = FALSE, ...) {

  # convert to spifa.list
  object <- as_list(object)

  # Information of model inference
  info <- attr(object, "model_info")

  # Prediction I: for the observed subjects
  if (info$model_type %in% c("eifa", "cifa") |
      (info$model_type == "cifa_pred" & is.null(newdata)) |
      (info$model_type == "spifa" & is.null(newcoords)) |
      (info$model_type == "spifa_pred" & is.null(newcoords) & is.null(newdata))) {
    return("here is only the means of the latent abilities")
  }

  # Prediction II: for the new subjects or new locations

  # Distances between predictive locations
  if (is.null(newcoords)) {
    newdist <- matrix(NA)
    cross_distances <- matrix(NA)
  } else {
    npred1 <- nrow(newcoords)
    newdist <- as.matrix(dist(newcoords))
      if (inherits(info$coordinates, "sfc")) {
        info$coordinates <- sf::st_transform(info$coordinates, crs = 3857) %>%
          sf::st_coordinates()
      }
    cross_distances <- as.matrix(pdist::pdist(newcoords, as.matrix(info$coordinates)))
  }

  # New data about predictors
  if (is.null(newdata)) {
    npred2 <- NULL
  } else {
    npred2 <- nrow(newdata)
  }

  # Obtain number of subjects or locations to predict
  if (!is.null(npred2) && exists("npred1")) {
    if (npred1 == npred2) {
      npred = npred1
    } else {
      stop(sprintf("number of rows of '%s' of '%s' must be the same",
                   "newcoords", "newdata"))
    }
  } else if (exists("npred1")) {
    npred = npred1
  } else if (!is.null(npred2)) {
    npred = npred2
  }

  # Build predictors for the new locations/subjects. If the model has
  # predictors but newdata was not supplied (e.g. predicting the spatial
  # component only), fall back to zeros so the predictor contribution is
  # held at its reference level instead of crashing with mismatched
  # dimensions.
  if (!is.null(newdata)) {
    newpredictors <- newdata
  } else if (info$model_type %in% c("cifa_pred", "spifa_pred")) {
    newpredictors <- matrix(0, npred, ncol(info$predictors))
  } else {
    newpredictors <- matrix(NA)
  }

  # Information about number of posterior samples to use
  nsamples <- nrow(object$z)
  # if (is.null(burnin)) burnin <- as.integer(nsamples / 2)
  # if (is.null(thin)) thin <- as.integer( (nsamples - burnin) / 1000)

  # blocks not sampled for this model_type (e.g. mgp_sd/mgp_phi for a
  # non-spatial fit, betas with no predictors) are absent from `object`
  # (dropped in spifa(), see R/spifa.R) rather than kept NA-filled; the C++
  # side still expects a placeholder matrix argument, so fall back to
  # matrix(NA) for whichever of these are missing.
  as_pred_mat <- function (block) if (is.null(object[[block]])) matrix(NA) else t(object[[block]])

  # List of options to call c++ function to predict
  pred_list <- list(samples_theta = t(object$theta),
    samples_corr_chol = t(object$corr_chol), samples_corr = t(object$corr),
    samples_mgp_sd = as_pred_mat("mgp_sd"), samples_mgp_phi = as_pred_mat("mgp_phi"),
    samples_betas = as_pred_mat("betas"),
    response = info$response, predictors = info$predictors, newpredictors = newpredictors,
    distances = info$distances, newdist = newdist, cross_distances = cross_distances,
    nobs = info$nobs, nitems = info$nitems, nfactors = info$nfactors, ngp = info$ngp,
    npred = npred, niter = nsamples, burnin = burnin, thin = thin,
    constrain_L = info$constrain_L, constrain_T = info$constrain_T,
    constrain_V_sd = info$constrain_V_sd,
    model_type = info$model_type
    )

  # Predict calling c++ predict_spifa_cpp
  prediction <- do.call(predict_spifa_cpp, pred_list)

  return(prediction)
}
